// Generated by `cargo xtask bindings` (tauri-specta). Do not edit.
// @ts-nocheck
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Returns the app name and version. */
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
};

/* Types */
/**  Static information about the running app. */
export type AppInfo = {
	/**  Product name. */
	name: string,
	/**  Crate version. */
	version: string,
};

/**
 *  SHA-256 of a server's leaf certificate DER, used for TOFU pinning.
 * 
 *  `Display` and `FromStr` use the `grdctl status` format: 32 lowercase hex byte pairs
 *  separated by `:` (for example `f3:e7:a2:…`), so users can compare the two directly.
 *  Serialized (serde) as that same string.
 */
export type CertFingerprint = string;

/**  Clipboard synchronisation level. */
export type ClipboardPrefs = 
/**  No clipboard channel traffic. */
"off" | 
/**  Text only. */
"text" | 
/**  Text and images (PNG/TIFF/DIB). Default. */
"text-and-images";

/**  What the Mac Command key is sent as. */
export type CmdAs = 
/**  Left/right Windows ("Super") key, scancode `0x5B`/`0x5C` extended. Default. */
"super" | 
/**  Control, scancode `0x1D`. */
"ctrl";

/**  How Drift reaches the GNOME session (plan §1.2). */
export type ConnectMode = 
/**  System daemon: NLA leg, then RDSTLS legs through the GDM greeter. */
"remote-login" | 
/**  Persistent per-user headless session with fixed RDP credentials. */
"headless" | 
/**  The user's Desktop Sharing daemon mirroring an existing session (no DISP channel). */
"desktop-sharing";

/**  Sub-stage of a connection leg, for progress display. */
export type ConnectStage = 
/**  TCP connect. */
"tcp" | 
/**  TLS handshake and certificate verification. */
"tls" | 
/**  NLA (CredSSP/NTLM), leg 1 and Headless/Sharing. */
"nla" | 
/**  RDSTLS with one-time redirect credentials (Remote Login legs ≥ 2). */
"rdstls" | 
/**  MCS / capability exchange / finalization. */
"activation";

/**  A saved connection (plan §3). Contains no secrets. */
export type ConnectionProfile = ConnectionProfile_Serialize | ConnectionProfile_Deserialize;

/**  A saved connection (plan §3). Contains no secrets. */
export type ConnectionProfile_Deserialize = {
	/**  Stable identifier; also the Keychain account key prefix. */
	id: string,
	/**  Display name (tab title). */
	name: string,
	/**  Host name or IP address. */
	host: string,
	/**  TCP port (RemoteLogin default 3389). */
	port: number,
	/**  Connection mode. */
	mode: ConnectMode,
	/**  RDP user: system credentials (RemoteLogin) or daemon credentials (Headless/Sharing). */
	rdp_username: string,
	/**  RemoteLogin only: the Linux user, shown in the greeter hint. */
	linux_username?: string | null,
	/**  TOFU-pinned certificate fingerprint of the first leg. */
	cert_pin?: CertFingerprint | null,
	/**  Keyboard preferences. */
	keyboard?: KeyboardPrefs,
	/**  Display preferences. */
	display?: DisplayPrefs,
	/**  Clipboard preferences. */
	clipboard?: ClipboardPrefs,
};

/**  A saved connection (plan §3). Contains no secrets. */
export type ConnectionProfile_Serialize = {
	/**  Stable identifier; also the Keychain account key prefix. */
	id: string,
	/**  Display name (tab title). */
	name: string,
	/**  Host name or IP address. */
	host: string,
	/**  TCP port (RemoteLogin default 3389). */
	port: number,
	/**  Connection mode. */
	mode: ConnectMode,
	/**  RDP user: system credentials (RemoteLogin) or daemon credentials (Headless/Sharing). */
	rdp_username: string,
	/**  RemoteLogin only: the Linux user, shown in the greeter hint. */
	linux_username?: string | null,
	/**  TOFU-pinned certificate fingerprint of the first leg. */
	cert_pin?: CertFingerprint | null,
	/**  Keyboard preferences. */
	keyboard: KeyboardPrefs,
	/**  Display preferences. */
	display: DisplayPrefs,
	/**  Clipboard preferences. */
	clipboard: ClipboardPrefs,
};

/**  Why a session stopped (plan §3). */
export type DisconnectReason = 
/**  Transport-level failure (reset, unreachable, DNS). Retryable. */
{ kind: "network" } | 
/**  TLS stream closed without close_notify. Retryable. */
{ kind: "tls-eof" } | 
/**  The server shut the session down (e.g. daemon restart). Retryable. */
{ kind: "server-shutdown" } | 
/**  A connect or protocol timeout. Retryable. */
{ kind: "timeout" } | 
/**  NLA rejected the credentials. Not retryable. */
{ kind: "auth-failed" } | 
/**  RDSTLS AuthResponse returned a non-zero result (e.g. `0x52E`). Not retryable. */
{ kind: "rdstls-failed"; detail: number } | 
/**  The server certificate does not match the pin / redirect target certificate. */
{ kind: "cert-mismatch" } | 
/**  Malformed or unexpected server data. */
{ kind: "protocol-error"; detail: string } | 
/**  More than [`MAX_REDIRECTS`] redirections in one attempt. */
{ kind: "redirect-loop" } | 
/**  The user closed the tab or cancelled. */
{ kind: "user-closed" } | 
/**  The remote user logged off. */
{ kind: "logged-off-remotely" } | 
/**  macOS Local Network Privacy denied the connection (`EHOSTUNREACH`, errno 65). */
{ kind: "local-network-denied" };

/**  Display preferences. */
export type DisplayPrefs = {
	/**  Resize the remote desktop to follow the window (Display Control). */
	adaptive?: boolean,
	/**  Use physical pixels with `DesktopScaleFactor=200` on Retina displays. */
	retina?: boolean,
};

/**  Keyboard preferences. */
export type KeyboardPrefs = {
	/**  Mapping of the Command key. */
	cmd_as?: CmdAs,
	/**  "Type using Mac layout": printable keys without Ctrl/Cmd go out as Unicode events. */
	type_with_mac_layout?: boolean,
};

/**  Lifecycle of one session (tab), plan §3. */
export type SessionState = SessionState_Serialize | SessionState_Deserialize;

/**  Lifecycle of one session (tab), plan §3. */
export type SessionState_Deserialize = 
/**  Not started. */
({ state: "idle" }) & { attempt?: never; desktop?: never; leg?: never; next_in?: never; reason?: never; scale?: never; stage?: never } | 
/**  Establishing connection leg `leg` (1-based, `1..=MAX_LEG`). */
({ state: "connecting"; 
/**  Connection leg (1 = initial, ≥ 2 = after a Server Redirection). */
leg: number; 
/**  Progress within the leg. */
stage: ConnectStage }) & { attempt?: never; desktop?: never; next_in?: never; reason?: never; scale?: never } | 
/**  Remote Login: the GDM greeter is visible and the user must log in. */
({ state: "awaiting-greeter-login" }) & { attempt?: never; desktop?: never; leg?: never; next_in?: never; reason?: never; scale?: never; stage?: never } | 
/**  A live desktop is displayed. */
({ state: "connected"; 
/**  Remote desktop size in pixels. */
desktop: Size<number>; 
/**  `DesktopScaleFactor` in percent (100 or 200). */
scale: number }) & { attempt?: never; leg?: never; next_in?: never; reason?: never; stage?: never } | 
/**  Waiting to retry after a retryable disconnect. */
({ state: "reconnecting"; 
/**  1-based attempt number. */
attempt: number; 
/**  Delay until the next attempt (serialized as integer milliseconds). */
next_in: number; 
/**  The retryable reason that triggered reconnection. */
reason: DisconnectReason }) & { desktop?: never; leg?: never; scale?: never; stage?: never } | 
/**  Stopped; the user may reconnect manually. */
({ state: "disconnected"; 
/**  Why. */
reason: DisconnectReason }) & { attempt?: never; desktop?: never; leg?: never; next_in?: never; scale?: never; stage?: never } | 
/**  Stopped with an error that needs user action. */
({ state: "failed"; 
/**  Why. */
reason: DisconnectReason }) & { attempt?: never; desktop?: never; leg?: never; next_in?: never; scale?: never; stage?: never };

/**  Lifecycle of one session (tab), plan §3. */
export type SessionState_Serialize = 
/**  Not started. */
({ state: "idle" }) & { attempt?: never; desktop?: never; leg?: never; next_in?: never; reason?: never; scale?: never; stage?: never } | 
/**  Establishing connection leg `leg` (1-based, `1..=MAX_LEG`). */
({ state: "connecting"; 
/**  Connection leg (1 = initial, ≥ 2 = after a Server Redirection). */
leg: number; 
/**  Progress within the leg. */
stage: ConnectStage }) & { attempt?: never; desktop?: never; next_in?: never; reason?: never; scale?: never } | 
/**  Remote Login: the GDM greeter is visible and the user must log in. */
({ state: "awaiting-greeter-login" }) & { attempt?: never; desktop?: never; leg?: never; next_in?: never; reason?: never; scale?: never; stage?: never } | 
/**  A live desktop is displayed. */
({ state: "connected"; 
/**  Remote desktop size in pixels. */
desktop: Size<number>; 
/**  `DesktopScaleFactor` in percent (100 or 200). */
scale: number }) & { attempt?: never; leg?: never; next_in?: never; reason?: never; stage?: never } | 
/**  Waiting to retry after a retryable disconnect. */
({ state: "reconnecting"; 
/**  1-based attempt number. */
attempt: number; 
/**  Delay until the next attempt (serialized as integer milliseconds). */
next_in: number; 
/**  The retryable reason that triggered reconnection. */
reason: DisconnectReason }) & { desktop?: never; leg?: never; scale?: never; stage?: never } | 
/**  Stopped; the user may reconnect manually. */
({ state: "disconnected"; 
/**  Why. */
reason: DisconnectReason }) & { attempt?: never; desktop?: never; leg?: never; next_in?: never; scale?: never; stage?: never } | 
/**  Stopped with an error that needs user action. */
({ state: "failed"; 
/**  Why. */
reason: DisconnectReason }) & { attempt?: never; desktop?: never; leg?: never; next_in?: never; scale?: never; stage?: never };

/**  A 2-D size. `Size<u32>` is used for pixels, `Size<f64>` for AppKit points. */
export type Size<T> = {
	/**  Horizontal extent. */
	width: T,
	/**  Vertical extent. */
	height: T,
};

