// Generated by `cargo xtask bindings` (tauri-specta). Do not edit.
// @ts-nocheck
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Returns the app name and version. */
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**  Lists saved profiles (sorted by name) with which passwords are stored. */
	listProfiles: () => typedError<ProfileEntry_Serialize[], CommandError>(__TAURI_INVOKE("list_profiles")),
	/**  A new, unsaved profile for `mode` with a fresh id and default settings. */
	newProfile: (mode: ConnectMode) => __TAURI_INVOKE<ConnectionProfile_Serialize>("new_profile", { mode }),
	/**  Validates a profile without saving it; an empty list means valid. */
	validateProfile: (profile: ConnectionProfile_Deserialize) => __TAURI_INVOKE<ProfileIssue[]>("validate_profile", { profile }),
	/**  Saves (inserts or updates) a profile and applies password changes. */
	saveProfile: (profile: ConnectionProfile_Deserialize, secrets: SecretsUpdate) => typedError<ProfileEntry_Serialize, CommandError>(__TAURI_INVOKE("save_profile", { profile, secrets })),
	/**
	 *  Deletes a profile, its stored passwords and its window frame; an open profile's window is
	 *  closed first (without asking).
	 */
	deleteProfile: (id: string) => typedError<null, CommandError>(__TAURI_INVOKE("delete_profile", { id })),
	/**  Clears a profile's pinned certificate (after a legitimate certificate change). */
	forgetCertificate: (id: string) => typedError<ProfileEntry_Serialize, CommandError>(__TAURI_INVOKE("forget_certificate", { id })),
	/**  Explains a disconnect reason for a mode (title, message, next steps, actions). */
	explain: (reason: DisconnectReason, mode: ConnectMode) => __TAURI_INVOKE<ErrorExplanation>("explain", { reason, mode }),
	/**  Opens System Settings › Privacy & Security › Local Network (errno 65 screen). */
	openLocalNetworkSettings: () => typedError<null, CommandError>(__TAURI_INVOKE("open_local_network_settings")),
	/**
	 *  Connects `profile_id`: opens a session window for it, or brings its window forward if it
	 *  already has one (from any window).
	 */
	connect: (profileId: string) => typedError<null, CommandError>(__TAURI_INVOKE("connect", { profileId })),
	/**  Trusts the prompted certificate (`pin` = remember it for this profile). */
	acceptCertificate: (fingerprint: CertFingerprint, pin: boolean) => typedError<null, CommandError>(__TAURI_INVOKE("accept_certificate", { fingerprint, pin })),
	/**  Rejects the prompted certificate (the session fails with `CertMismatch`). */
	rejectCertificate: () => typedError<null, CommandError>(__TAURI_INVOKE("reject_certificate")),
	/**  Skips the backoff delay and reconnects now ("Now" button, error screen "Reconnect"). */
	reconnectNow: () => typedError<null, CommandError>(__TAURI_INVOKE("reconnect_now")),
	/**  Stops reconnecting; the session stays disconnected ("Cancel" button). */
	cancelReconnect: () => typedError<null, CommandError>(__TAURI_INVOKE("cancel_reconnect")),
	/**
	 *  Closes the calling session window without asking (the error sheet's Close, Cancel while
	 *  connecting): the session closes gracefully, then the window.
	 */
	closeSession: () => typedError<null, CommandError>(__TAURI_INVOKE("close_session")),
	/**
	 *  Gives the keyboard back to the calling window's page or live picture (the title bar never
	 *  keeps it).
	 */
	focusContent: () => typedError<null, CommandError>(__TAURI_INVOKE("focus_content")),
	/**
	 *  Copies a profile and its stored passwords under a new id, named "<name> copy", without the
	 *  certificate pin.
	 */
	duplicateProfile: (id: string) => typedError<ProfileEntry_Serialize, CommandError>(__TAURI_INVOKE("duplicate_profile", { id })),
	/**  The profiles that have a session window (pulled by the Connections page on load). */
	connections: () => typedError<Connections, CommandError>(__TAURI_INVOKE("connections")),
	/**  Brings `profile_id`'s session window forward; `NotFound` if it has none. */
	showWindow: (profileId: string) => typedError<null, CommandError>(__TAURI_INVOKE("show_window", { profileId })),
	/**
	 *  Closes `profile_id`'s session window without asking (the card's Disconnect); `NotFound` if
	 *  it has none.
	 */
	disconnectProfile: (profileId: string) => typedError<null, CommandError>(__TAURI_INVOKE("disconnect_profile", { profileId })),
	/**
	 *  Shows the Connections window and makes it key; with `edit`, opens that profile's edit sheet
	 *  (the title bar's grid button, the error sheet's Edit Connection…).
	 */
	showConnections: (edit: string | null) => typedError<null, CommandError>(__TAURI_INVOKE("show_connections", { edit })),
	/**  Shows the Connections window with the New Connection sheet. */
	newConnection: () => typedError<null, CommandError>(__TAURI_INVOKE("new_connection")),
	/**  The calling session window's identity (pulled by its title bar and its page on load). */
	windowIdentity: () => typedError<WindowIdentity, CommandError>(__TAURI_INVOKE("window_identity")),
	/**  Turns the calling session window's statistics HUD on or off (the title bar's gauge). */
	toggleStats: () => typedError<null, CommandError>(__TAURI_INVOKE("toggle_stats")),
};

/** Events */
export const events = {
	connectionsChanged: makeEvent<ConnectionsChanged>("connections-changed"),
	connectionsIntentRequested: makeEvent<ConnectionsIntentRequested>("connections-intent-requested"),
	sessionViewChanged: makeEvent<SessionViewChanged_Deserialize>("session-view-changed"),
	thumbnailUpdated: makeEvent<ThumbnailUpdated>("thumbnail-updated"),
	windowIdentityChanged: makeEvent<WindowIdentityChanged>("window-identity-changed"),
};

/* Types */
/**  Static information about the running app. */
export type AppInfo = {
	/**  Product name. */
	name: string,
	/**  Crate version. */
	version: string,
};

/**
 *  SHA-256 of a server's leaf certificate DER, used for TOFU pinning.
 * 
 *  `Display` and `FromStr` use the `grdctl status` format: 32 lowercase hex byte pairs
 *  separated by `:` (for example `f3:e7:a2:…`), so users can compare the two directly.
 *  Serialized (serde) as that same string.
 */
export type CertFingerprint = string;

/**  A pending certificate decision. */
export type CertificatePrompt = {
	/**  Host as shown to the user. */
	host: string,
	/**  Port. */
	port: number,
	/**  SHA-256 of the leaf certificate, in `grdctl status` format. */
	fingerprint: CertFingerprint,
	/**  Which certificate. */
	subject: CertificateSubject,
	/**  The command that prints the same fingerprint on the host, for this mode. */
	grdctl_command: string,
};

/**  Which certificate a prompt is about. */
export type CertificateSubject = 
/**  The host in the profile. */
"server" | 
/**  A Server Redirection target (Remote Login legs ≥ 2). */
"redirect-target";

/**  Clipboard synchronisation level. */
export type ClipboardPrefs = 
/**  No clipboard channel traffic. */
"off" | 
/**  Text only. */
"text" | 
/**  Text and images (PNG/TIFF/DIB). Default. */
"text-and-images";

/**  What the Mac Command key is sent as. */
export type CmdAs = 
/**  Left/right Windows ("Super") key, scancode `0x5B`/`0x5C` extended. Default. */
"super" | 
/**  Control, scancode `0x1D`. */
"ctrl";

/**  Errors returned to the webview by profile commands. */
export type CommandError = 
/**  The profile failed validation. */
{ kind: "invalid"; 
/**  Per-field problems. */
issues: ProfileIssue[] } | 
/**  No profile with the given id. */
{ kind: "not-found" } | 
/**  Reading or writing profiles or passwords failed. */
{ kind: "storage"; 
/**  Human-readable cause (never contains secrets). */
message: string } | 
/**  A macOS facility (e.g. opening System Settings) failed. */
{ kind: "platform"; 
/**  Human-readable cause. */
message: string } | 
/**  The window has no session (or it has already ended). */
{ kind: "no-session" } | 
/**  The command exists for the UI but its backend is not wired yet. */
{ kind: "not-implemented"; 
/**  What is missing. */
what: string };

/**  How Drift reaches the GNOME session (plan §1.2). */
export type ConnectMode = 
/**  System daemon: NLA leg, then RDSTLS legs through the GDM greeter. */
"remote-login" | 
/**  Persistent per-user headless session with fixed RDP credentials. */
"headless" | 
/**  The user's Desktop Sharing daemon mirroring an existing session (no DISP channel). */
"desktop-sharing";

/**  Sub-stage of a connection leg, for progress display. */
export type ConnectStage = 
/**  TCP connect. */
"tcp" | 
/**  TLS handshake and certificate verification. */
"tls" | 
/**  NLA (CredSSP/NTLM), leg 1 and Headless/Sharing. */
"nla" | 
/**  RDSTLS with one-time redirect credentials (Remote Login legs ≥ 2). */
"rdstls" | 
/**  MCS / capability exchange / finalization. */
"activation";

/**  A saved connection (plan §3). Contains no secrets. */
export type ConnectionProfile = ConnectionProfile_Serialize | ConnectionProfile_Deserialize;

/**  A saved connection (plan §3). Contains no secrets. */
export type ConnectionProfile_Deserialize = {
	/**  Stable identifier; also the Keychain account key prefix. */
	id: string,
	/**  Display name (window title). */
	name: string,
	/**  Host name or IP address. */
	host: string,
	/**  TCP port (RemoteLogin default 3389). */
	port: number,
	/**  Connection mode. */
	mode: ConnectMode,
	/**  RDP user: system credentials (RemoteLogin) or daemon credentials (Headless/Sharing). */
	rdp_username: string,
	/**  RemoteLogin only: the Linux user, shown in the greeter hint. */
	linux_username?: string | null,
	/**  TOFU-pinned certificate fingerprint of the first leg. */
	cert_pin?: CertFingerprint | null,
	/**  Keyboard preferences. */
	keyboard?: KeyboardPrefs,
	/**  Display preferences. */
	display?: DisplayPrefs,
	/**  Clipboard preferences. */
	clipboard?: ClipboardPrefs,
};

/**  A saved connection (plan §3). Contains no secrets. */
export type ConnectionProfile_Serialize = {
	/**  Stable identifier; also the Keychain account key prefix. */
	id: string,
	/**  Display name (window title). */
	name: string,
	/**  Host name or IP address. */
	host: string,
	/**  TCP port (RemoteLogin default 3389). */
	port: number,
	/**  Connection mode. */
	mode: ConnectMode,
	/**  RDP user: system credentials (RemoteLogin) or daemon credentials (Headless/Sharing). */
	rdp_username: string,
	/**  RemoteLogin only: the Linux user, shown in the greeter hint. */
	linux_username?: string | null,
	/**  TOFU-pinned certificate fingerprint of the first leg. */
	cert_pin?: CertFingerprint | null,
	/**  Keyboard preferences. */
	keyboard: KeyboardPrefs,
	/**  Display preferences. */
	display: DisplayPrefs,
	/**  Clipboard preferences. */
	clipboard: ClipboardPrefs,
};

/**  Where a profile's connection stands (gallery pills, Dock menu, Window menu, identity capsule). */
export type ConnectionStatus = 
/**  No session window. */
"idle" | 
/**  Connecting, or waiting for a certificate decision (spinner). */
"connecting" | 
/**  The picture (or the GNOME login screen) is live (green). */
"live" | 
/**  Waiting out a reconnect backoff (amber). */
"reconnecting" | 
/**  Failed or disconnected with an explanation (red). */
"failed";

/**  Everything the Connections window needs besides the profile list. */
export type Connections = {
	/**  Profiles with a session window, in window opening order. */
	open: OpenConnection[],
};

/**  Emitted to the `connections` page after any status change, window open or close. */
export type ConnectionsChanged = Connections;

/**  What the Connections page should open when Rust brings it forward. */
export type ConnectionsIntent = 
/**  The New Connection sheet (Cmd+N, Dock ▸ New Connection…). */
{ kind: "new" } | 
/**  The edit sheet of a profile (Cmd+E, the error sheet's Edit Connection…). */
{ kind: "edit"; 
/**  The profile to edit. */
profile_id: string };

/**  Emitted to the `connections` page to open a sheet. */
export type ConnectionsIntentRequested = ConnectionsIntent;

/**  Why a session stopped (plan §3). */
export type DisconnectReason = 
/**  Transport-level failure (reset, unreachable, DNS). Retryable. */
{ kind: "network" } | 
/**  TLS stream closed without close_notify. Retryable. */
{ kind: "tls-eof" } | 
/**  The server shut the session down (e.g. daemon restart). Retryable. */
{ kind: "server-shutdown" } | 
/**  A connect or protocol timeout. Retryable. */
{ kind: "timeout" } | 
/**  NLA rejected the credentials. Not retryable. */
{ kind: "auth-failed" } | 
/**  RDSTLS AuthResponse returned a non-zero result (e.g. `0x52E`). Not retryable. */
{ kind: "rdstls-failed"; detail: number } | 
/**  The server certificate does not match the pin / redirect target certificate. */
{ kind: "cert-mismatch" } | 
/**  Malformed or unexpected server data. */
{ kind: "protocol-error"; detail: string } | 
/**  More than [`MAX_REDIRECTS`] redirections in one attempt. */
{ kind: "redirect-loop" } | 
/**  The user closed the window or cancelled. */
{ kind: "user-closed" } | 
/**  The remote user logged off. */
{ kind: "logged-off-remotely" } | 
/**  macOS Local Network Privacy denied the connection (`EHOSTUNREACH`, errno 65). */
{ kind: "local-network-denied" };

/**  Display preferences. */
export type DisplayPrefs = {
	/**  Resize the remote desktop to follow the window (Display Control). */
	adaptive?: boolean,
	/**  Use physical pixels with `DesktopScaleFactor=200` on Retina displays. */
	retina?: boolean,
};

/**  A button offered on an error screen. */
export type ErrorAction = 
/**  Connect again. */
"reconnect" | 
/**  Open the profile form. */
"edit-profile" | 
/**  Open System Settings › Privacy & Security › Local Network. */
"open-local-network-settings" | 
/**  Close the window. */
"close";

/**  What went wrong, in words, and what the user can do about it. */
export type ErrorExplanation = {
	/**  Short headline. */
	title: string,
	/**  One or two sentences describing the problem. */
	message: string,
	/**  Concrete next steps, in order. */
	next_steps: string[],
	/**  Buttons to offer; the first is the default. */
	actions: ErrorAction[],
};

/**  Keyboard preferences. */
export type KeyboardPrefs = {
	/**  Mapping of the Command key. */
	cmd_as?: CmdAs,
	/**  "Type using Mac layout": printable keys without Ctrl/Cmd go out as Unicode events. */
	type_with_mac_layout?: boolean,
};

/**  What to do with the Linux greeter password on save. */
export type LinuxPasswordUpdate = 
/**  Leave as is. */
{ action: "keep" } | 
/**  Opt in: store this password and type it into the greeter. */
{ action: "store"; password: string } | 
/**  Opt out: delete the stored password. */
{ action: "forget" };

/**  One profile that has a session window (the gallery's "Open" section). */
export type OpenConnection = {
	/**  The profile. */
	profile_id: string,
	/**  Its window's label (`session-<n>`). */
	window: string,
	/**  Where the connection stands. */
	status: ConnectionStatus,
	/**  Uptime in seconds at emit time while live (the UI ticks locally). */
	live_secs: number | null,
	/**  Seconds until the next attempt while reconnecting. */
	reconnect_in_secs: number | null,
	/**  The reconnect attempt while reconnecting. */
	attempt: number | null,
};

/**  A profile plus which passwords are stored for it (never the passwords themselves). */
export type ProfileEntry = ProfileEntry_Serialize | ProfileEntry_Deserialize;

/**  A profile plus which passwords are stored for it (never the passwords themselves). */
export type ProfileEntry_Deserialize = {
	/**  The profile. */
	profile: ConnectionProfile_Deserialize,
	/**  An RDP password is stored for the profile's mode. */
	has_rdp_password: boolean,
	/**  Remote Login: a Linux password is stored (the user opted in to greeter typing). */
	has_linux_password: boolean,
};

/**  A profile plus which passwords are stored for it (never the passwords themselves). */
export type ProfileEntry_Serialize = {
	/**  The profile. */
	profile: ConnectionProfile_Serialize,
	/**  An RDP password is stored for the profile's mode. */
	has_rdp_password: boolean,
	/**  Remote Login: a Linux password is stored (the user opted in to greeter typing). */
	has_linux_password: boolean,
};

/**  A profile field that can fail validation. */
export type ProfileField = 
/**  [`ConnectionProfile::name`]. */
"name" | 
/**  [`ConnectionProfile::host`]. */
"host" | 
/**  [`ConnectionProfile::port`]. */
"port" | 
/**  [`ConnectionProfile::rdp_username`]. */
"rdp-username" | 
/**  [`ConnectionProfile::linux_username`]. */
"linux-username";

/**  One validation failure, with a user-facing message. */
export type ProfileIssue = {
	/**  The offending field. */
	field: ProfileField,
	/**  What is wrong. */
	problem: ProfileProblem,
	/**  A sentence for the UI, shown next to the field. */
	message: string,
};

/**  What is wrong with a field. */
export type ProfileProblem = 
/**  Required but empty (or only whitespace). */
"empty" | 
/**  Longer than allowed. */
"too-long" | 
/**  Leading or trailing whitespace. */
"surrounding-whitespace" | 
/**  Contains control characters or characters not allowed for this field. */
"invalid-characters" | 
/**  The host is not a valid IPv4/IPv6 address or DNS name. */
"invalid-host" | 
/**  The host contains a port (`host:3389`); use the port field. */
"port-in-host" | 
/**  The host contains a URL scheme (`rdp://`). */
"scheme-in-host" | 
/**  Port 0 is not a valid TCP port. */
"invalid-port" | 
/**  The field does not apply to the profile's mode. */
"not-applicable";

/**  Which screen the webview shows for a session window. */
export type Screen = 
/**  No session: the connect / profiles form. */
"profiles" | 
/**  Connecting progress. */
"connecting" | 
/**  An unknown certificate needs a decision. */
"certificate" | 
/**  Remote Login greeter is live: a non-modal hint banner over the picture. */
"greeter-hint" | 
/**  Backoff overlay over the dimmed last frame: "Reconnecting in N s… [Now] [Cancel]". */
"reconnecting" | 
/**  Ended with an explanation and next steps. */
"error" | 
/**  Live desktop: the webview is hidden, unless the statistics HUD is switched on. */
"live";

/**  Password changes submitted with a profile. Empty strings mean "unchanged". */
export type SecretsUpdate = {
	/**  New RDP password for the profile's mode (`None` = keep the stored one). */
	rdp_password: string | null,
	/**  Linux password opt-in (Remote Login only; ignored and forgotten for other modes). */
	linux_password: LinuxPasswordUpdate,
};

/**  Lifecycle of one session (window), plan §3. */
export type SessionState = SessionState_Serialize | SessionState_Deserialize;

/**  Lifecycle of one session (window), plan §3. */
export type SessionState_Deserialize = 
/**  Not started. */
({ state: "idle" }) & { attempt?: never; desktop?: never; leg?: never; next_in?: never; reason?: never; scale?: never; stage?: never } | 
/**  Establishing connection leg `leg` (1-based, `1..=MAX_LEG`). */
({ state: "connecting"; 
/**  Connection leg (1 = initial, ≥ 2 = after a Server Redirection). */
leg: number; 
/**  Progress within the leg. */
stage: ConnectStage }) & { attempt?: never; desktop?: never; next_in?: never; reason?: never; scale?: never } | 
/**  Remote Login: the GDM greeter is visible and the user must log in. */
({ state: "awaiting-greeter-login" }) & { attempt?: never; desktop?: never; leg?: never; next_in?: never; reason?: never; scale?: never; stage?: never } | 
/**  A live desktop is displayed. */
({ state: "connected"; 
/**  Remote desktop size in pixels. */
desktop: Size<number>; 
/**  `DesktopScaleFactor` in percent (100 or 200). */
scale: number }) & { attempt?: never; leg?: never; next_in?: never; reason?: never; stage?: never } | 
/**  Waiting to retry after a retryable disconnect. */
({ state: "reconnecting"; 
/**  1-based attempt number. */
attempt: number; 
/**  Delay until the next attempt (serialized as integer milliseconds). */
next_in: number; 
/**  The retryable reason that triggered reconnection. */
reason: DisconnectReason }) & { desktop?: never; leg?: never; scale?: never; stage?: never } | 
/**  Stopped; the user may reconnect manually. */
({ state: "disconnected"; 
/**  Why. */
reason: DisconnectReason }) & { attempt?: never; desktop?: never; leg?: never; next_in?: never; scale?: never; stage?: never } | 
/**  Stopped with an error that needs user action. */
({ state: "failed"; 
/**  Why. */
reason: DisconnectReason }) & { attempt?: never; desktop?: never; leg?: never; next_in?: never; scale?: never; stage?: never };

/**  Lifecycle of one session (window), plan §3. */
export type SessionState_Serialize = 
/**  Not started. */
({ state: "idle" }) & { attempt?: never; desktop?: never; leg?: never; next_in?: never; reason?: never; scale?: never; stage?: never } | 
/**  Establishing connection leg `leg` (1-based, `1..=MAX_LEG`). */
({ state: "connecting"; 
/**  Connection leg (1 = initial, ≥ 2 = after a Server Redirection). */
leg: number; 
/**  Progress within the leg. */
stage: ConnectStage }) & { attempt?: never; desktop?: never; next_in?: never; reason?: never; scale?: never } | 
/**  Remote Login: the GDM greeter is visible and the user must log in. */
({ state: "awaiting-greeter-login" }) & { attempt?: never; desktop?: never; leg?: never; next_in?: never; reason?: never; scale?: never; stage?: never } | 
/**  A live desktop is displayed. */
({ state: "connected"; 
/**  Remote desktop size in pixels. */
desktop: Size<number>; 
/**  `DesktopScaleFactor` in percent (100 or 200). */
scale: number }) & { attempt?: never; leg?: never; next_in?: never; reason?: never; stage?: never } | 
/**  Waiting to retry after a retryable disconnect. */
({ state: "reconnecting"; 
/**  1-based attempt number. */
attempt: number; 
/**  Delay until the next attempt (serialized as integer milliseconds). */
next_in: number; 
/**  The retryable reason that triggered reconnection. */
reason: DisconnectReason }) & { desktop?: never; leg?: never; scale?: never; stage?: never } | 
/**  Stopped; the user may reconnect manually. */
({ state: "disconnected"; 
/**  Why. */
reason: DisconnectReason }) & { attempt?: never; desktop?: never; leg?: never; next_in?: never; scale?: never; stage?: never } | 
/**  Stopped with an error that needs user action. */
({ state: "failed"; 
/**  Why. */
reason: DisconnectReason }) & { attempt?: never; desktop?: never; leg?: never; next_in?: never; scale?: never; stage?: never };

/**  Everything a session window's webview needs to render. */
export type SessionView = SessionView_Serialize | SessionView_Deserialize;

/**  Emitted to a session window whenever its [`SessionView`] changes. */
export type SessionViewChanged = SessionViewChanged_Serialize | SessionViewChanged_Deserialize;

/**  Emitted to a session window whenever its [`SessionView`] changes. */
export type SessionViewChanged_Deserialize = SessionView_Deserialize;

/**  Emitted to a session window whenever its [`SessionView`] changes. */
export type SessionViewChanged_Serialize = SessionView_Serialize;

/**  Everything a session window's webview needs to render. */
export type SessionView_Deserialize = {
	/**  Profile display name. */
	profile_name: string,
	/**  Profile mode. */
	mode: ConnectMode,
	/**  Remote Login: the Linux user to log in as (greeter hint). */
	linux_username: string | null,
	/**  Current session state. */
	state: SessionState_Deserialize,
	/**  What to render. */
	screen: Screen,
	/**  Set while a certificate prompt is pending. */
	certificate: CertificatePrompt | null,
	/**  Set for `Disconnected` / `Failed` states. */
	explanation: ErrorExplanation | null,
	/**
	 *  Remote Login: the greeter appeared after this window had already shown a desktop, so the
	 *  session is still running ("log in to resume").
	 */
	resuming: boolean,
	/**  Reconnect attempt budget shown in the overlay (`None` = unlimited). */
	max_attempts: number | null,
	/**
	 *  The statistics HUD is switched on for this window (Session ▸ Show Statistics). It is a
	 *  per-window user choice, so no session event ever changes it.
	 */
	show_stats: boolean,
	/**  Latest statistics sample, or `None` before the first one and once the picture is gone. */
	stats: StatsView | null,
};

/**  Everything a session window's webview needs to render. */
export type SessionView_Serialize = {
	/**  Profile display name. */
	profile_name: string,
	/**  Profile mode. */
	mode: ConnectMode,
	/**  Remote Login: the Linux user to log in as (greeter hint). */
	linux_username: string | null,
	/**  Current session state. */
	state: SessionState_Serialize,
	/**  What to render. */
	screen: Screen,
	/**  Set while a certificate prompt is pending. */
	certificate: CertificatePrompt | null,
	/**  Set for `Disconnected` / `Failed` states. */
	explanation: ErrorExplanation | null,
	/**
	 *  Remote Login: the greeter appeared after this window had already shown a desktop, so the
	 *  session is still running ("log in to resume").
	 */
	resuming: boolean,
	/**  Reconnect attempt budget shown in the overlay (`None` = unlimited). */
	max_attempts: number | null,
	/**
	 *  The statistics HUD is switched on for this window (Session ▸ Show Statistics). It is a
	 *  per-window user choice, so no session event ever changes it.
	 */
	show_stats: boolean,
	/**  Latest statistics sample, or `None` before the first one and once the picture is gone. */
	stats: StatsView | null,
};

/**  A 2-D size. `Size<u32>` is used for pixels, `Size<f64>` for AppKit points. */
export type Size<T> = {
	/**  Horizontal extent. */
	width: T,
	/**  Vertical extent. */
	height: T,
};

/**
 *  One statistics sample, quantised to what the HUD actually prints.
 * 
 *  [`drift_rdp::SessionStats`] is sampled about once per second; the numbers are rounded to one
 *  decimal here so that two samples that would draw the same line compare equal and the view is
 *  not re-emitted (plan M1 "Done (manual M1)", M9-1).
 */
export type StatsView = {
	/**  Presented frames per second, in tenths (`589` prints as `58.9 fps`). */
	fps_tenths: number,
	/**  Received payload bit rate, in tenths of a Mbit/s. */
	mbit_tenths: number,
	/**  Decode + present latency, 95th percentile, in tenths of a millisecond. */
	latency_p95_tenths_ms: number,
	/**  Frames awaiting acknowledgement. */
	unacked_frames: number,
};

/**
 *  A live session's preview for its gallery card, as a `data:image/png;base64,…` URL.
 *  `image: None` drops the preview (the session ended). Never logged, never written to disk.
 */
export type Thumbnail = {
	/**  The profile whose card shows it. */
	profile_id: string,
	/**  The PNG as a data URL, or `None`. */
	image: string | null,
};

/**  Emitted to the `connections` page only, while it is visible. */
export type ThumbnailUpdated = Thumbnail;

/**  A session window's title bar: the identity capsule and the buttons. */
export type WindowIdentity = {
	/**  The window's profile. */
	profile_id: string,
	/**  Display name. */
	name: string,
	/**  Host as saved in the profile. */
	host: string,
	/**  Connection mode (picks the glyph). */
	mode: ConnectMode,
	/**  Dot or spinner. */
	status: ConnectionStatus,
	/**  Greeter hint (tooltip) while the GNOME login screen waits. */
	hint: string | null,
	/**  The statistics HUD is on (gauge pressed). */
	show_stats: boolean,
};

/**  Emitted to a session window's `<label>-titlebar` webview (identical pushes are skipped). */
export type WindowIdentityChanged = WindowIdentity;

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

