//! # drift-app
//!
//! The Tauri shell: IPC commands (typed with tauri-specta), saved profiles, the per-window
//! [`view::SessionView`] model, the `SessionManager`, windows, the tab strip ([`strip`]) and
//! menus.
//!
//! The TypeScript bindings in `ui/src/bindings.ts` are generated from [`specta_builder`]
//! by `cargo xtask bindings`; CI fails when they are stale.

pub mod commands;
mod host;
pub mod manager;
pub mod menu;
mod options;
pub mod platform;
pub mod present;
pub mod profiles;
#[cfg(feature = "recording")]
pub mod recording;
pub mod secrets;
pub mod services;
pub mod strip;
pub mod view;
pub mod windows;

pub use options::RunOptions;

use std::path::Path;
use std::sync::Arc;

use tauri::Manager as _;

/// The tauri-specta builder listing every IPC command, event and exported type.
pub fn specta_builder() -> tauri_specta::Builder<tauri::Wry> {
    tauri_specta::Builder::<tauri::Wry>::new()
        .commands(tauri_specta::collect_commands![
            commands::app_info,
            commands::list_profiles,
            commands::new_profile,
            commands::validate_profile,
            commands::save_profile,
            commands::delete_profile,
            commands::forget_certificate,
            commands::explain,
            commands::open_local_network_settings,
            commands::connect,
            commands::accept_certificate,
            commands::reject_certificate,
            commands::reconnect_now,
            commands::cancel_reconnect,
            commands::close_session,
            commands::disconnect,
            commands::tab_strip,
            commands::select_tab,
            commands::close_tab,
            commands::new_tab,
            commands::focus_content,
        ])
        .events(tauri_specta::collect_events![view::SessionViewChanged, strip::TabStripChanged])
        .typ::<drift_core::ConnectionProfile>()
        .typ::<drift_core::SessionState>()
        .typ::<view::SessionView>()
}

/// Writes the TypeScript bindings to `path`.
pub fn export_bindings(path: &Path) -> Result<(), String> {
    specta_builder()
        .export(
            specta_typescript::Typescript::default().header(
                "// Generated by `cargo xtask bindings` (tauri-specta). Do not edit.\n// @ts-nocheck",
            ),
            path,
        )
        .map_err(|e| e.to_string())
}

/// Runs the application with explicit options (tests, smoke tests).
///
/// # Panics
/// Panics if the Tauri runtime fails to start (unrecoverable at launch).
#[allow(clippy::expect_used)]
pub fn run_with(options: RunOptions) {
    init_logging();
    let RunOptions { config_dir, memory_secrets, secrets: secret_store, autoconnect, on_ready } = options;
    let builder = specta_builder();
    let on_ready = std::sync::Mutex::new(on_ready);
    let app = tauri::Builder::default()
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);
            let handle = app.handle().clone();
            let dir = match &config_dir {
                Some(dir) => dir.clone(),
                None => app.path().app_config_dir()?,
            };
            // Passwords live in the Keychain (drift-macos, M3-2); tests use memory.
            let secrets: Arc<dyn secrets::SecretStore> = match (&secret_store, memory_secrets) {
                (Some(store), _) => Arc::clone(store),
                (None, true) => Arc::new(secrets::MemorySecretStore::new()),
                (None, false) => Arc::new(secrets::KeychainSecretStore::new(drift_macos::Keychain::new())),
            };
            let profiles =
                Arc::new(profiles::ProfileService::open(profiles::ProfileFile::in_dir(&dir), secrets)?);
            let session_host = Arc::new(host::TauriHost::new(handle.clone(), profiles.clone()));
            let sessions =
                manager::SessionManager::new(session_host, tauri::async_runtime::handle().inner().clone());
            // The app-lifetime platform services: the 250 ms pasteboard poll (M5-3/M5-2) and
            // the network/wake reconnect triggers (M7-2). Both fan out to every live session,
            // so they belong to the app, not to one tab. Managed state keeps them alive.
            app.manage(services::PlatformServices::start(&handle, sessions.clone()));
            app.manage(commands::AppState::new(profiles.clone(), sessions));
            app.set_menu(windows::build_menu(&handle)?)?;
            let first_profile = autoconnect.as_deref().and_then(|name| {
                let all = profiles.profiles().unwrap_or_default();
                present::find_autoconnect(&all, name).map(|p| p.id)
            });
            if autoconnect.is_some() && first_profile.is_none() {
                tracing::warn!("DRIFT_AUTOCONNECT names no saved profile");
            }
            windows::open_tab_with(&handle, first_profile);
            if let Some(ready) = on_ready.lock().ok().and_then(|mut r| r.take()) {
                ready(handle);
            }
            Ok(())
        })
        .on_menu_event(|app, event| {
            if let Some(action) = menu::MenuAction::from_id(&event.id().0) {
                windows::run_menu_action(app, action);
            }
        })
        .on_window_event(|window, event| {
            if let tauri::WindowEvent::CloseRequested { api, .. } = event {
                let label = window.label().to_owned();
                let app = window.app_handle();
                if !app.state::<commands::AppState>().is_closing(&label) {
                    // Close the session first (graceful, capped), then destroy the window.
                    api.prevent_close();
                    windows::close_tab(app, &label);
                }
            }
        })
        .build(tauri::generate_context!())
        .expect("error while starting Drift");

    app.run(|handle, event| match event {
        // Closing the last tab leaves Drift running, like other Mac apps; Cmd+Q exits.
        tauri::RunEvent::ExitRequested { code, api, .. } if code.is_none() => api.prevent_exit(),
        tauri::RunEvent::Reopen { has_visible_windows, .. } if !has_visible_windows => {
            windows::open_tab(handle);
        }
        tauri::RunEvent::Exit => windows::shutdown_blocking(handle),
        _ => {}
    });
}

/// Sets up `tracing` (`RUST_LOG`, default `info`). Secrets never reach a log: Drift's own
/// passwords live in `Zeroizing` values whose `Debug` is redacted (ADR M0-5) and are never
/// formatted here, and the third-party targets that *do* log credentials below `INFO` are
/// capped by `drift_rdp::logging` whatever `RUST_LOG` asks for (M9-3).
fn init_logging() {
    use tracing_subscriber::layer::SubscriberExt as _;
    use tracing_subscriber::util::SubscriberInitExt as _;
    use tracing_subscriber::{EnvFilter, filter};

    let env = EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("info"));
    // Second global filter: `RUST_LOG` chooses verbosity, this one refuses the targets that
    // log credentials below INFO, whatever `RUST_LOG` asked for (M9-3).
    let credentials = filter::filter_fn(|m| drift_rdp::logging::allows(m.target(), *m.level()));
    let _ = tracing_subscriber::registry()
        .with(env)
        .with(credentials)
        .with(tracing_subscriber::fmt::layer())
        .try_init();
}

/// Runs the application (called from `main`).
pub fn run() {
    run_with(RunOptions::from_env());
}
