//! # drift-app
//!
//! The Tauri shell: IPC commands (typed with tauri-specta), saved profiles, the per-window
//! [`view::SessionView`] model, and later the `SessionManager`, windows/tabs and menus (M6-*).
//!
//! The TypeScript bindings in `ui/src/bindings.ts` are generated from [`specta_builder`]
//! by `cargo xtask bindings`; CI fails when they are stale.

pub mod commands;
pub mod manager;
pub mod menu;
mod options;
pub mod platform;
pub mod present;
pub mod profiles;
pub mod secrets;
pub mod view;
pub mod windows;

pub use options::RunOptions;

use std::path::Path;
use std::sync::Arc;

use tauri::Manager as _;

/// The tauri-specta builder listing every IPC command, event and exported type.
pub fn specta_builder() -> tauri_specta::Builder<tauri::Wry> {
    tauri_specta::Builder::<tauri::Wry>::new()
        .commands(tauri_specta::collect_commands![
            commands::app_info,
            commands::list_profiles,
            commands::new_profile,
            commands::validate_profile,
            commands::save_profile,
            commands::delete_profile,
            commands::forget_certificate,
            commands::explain,
            commands::open_local_network_settings,
            commands::connect,
            commands::accept_certificate,
            commands::reject_certificate,
            commands::reconnect_now,
            commands::cancel_reconnect,
            commands::close_session,
        ])
        .events(tauri_specta::collect_events![view::SessionViewChanged])
        .typ::<drift_core::ConnectionProfile>()
        .typ::<drift_core::SessionState>()
        .typ::<view::SessionView>()
}

/// Writes the TypeScript bindings to `path`.
pub fn export_bindings(path: &Path) -> Result<(), String> {
    specta_builder()
        .export(
            specta_typescript::Typescript::default().header(
                "// Generated by `cargo xtask bindings` (tauri-specta). Do not edit.\n// @ts-nocheck",
            ),
            path,
        )
        .map_err(|e| e.to_string())
}

/// Runs the application with explicit options (tests, smoke tests).
pub fn run_with(options: RunOptions) {
    let _ = options;
    todo!("M6-2")
}

/// Runs the application (called from `main`).
///
/// # Panics
/// Panics if the Tauri runtime fails to start (unrecoverable at launch).
pub fn run() {
    let builder = specta_builder();
    #[allow(clippy::expect_used)]
    tauri::Builder::default()
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);
            let config_dir = app.path().app_config_dir()?;
            // Passwords live in the Keychain (drift-macos, M3-2).
            let secrets = Arc::new(secrets::KeychainSecretStore::new(drift_macos::Keychain::new()));
            let profiles =
                profiles::ProfileService::open(profiles::ProfileFile::in_dir(&config_dir), secrets)?;
            app.manage(commands::AppState { profiles });
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running Drift");
}
