//! # drift-app
//!
//! The Tauri shell: IPC commands (typed with tauri-specta), and later the
//! `SessionManager`, windows/tabs and menus (M1-6, M6-*).
//!
//! The TypeScript bindings in `ui/src/bindings.ts` are generated from [`specta_builder`]
//! by `cargo xtask bindings`; CI fails when they are stale.

pub mod commands;

use std::path::Path;

/// The tauri-specta builder listing every IPC command and exported type.
pub fn specta_builder() -> tauri_specta::Builder<tauri::Wry> {
    tauri_specta::Builder::<tauri::Wry>::new()
        .commands(tauri_specta::collect_commands![commands::app_info])
        .typ::<drift_core::ConnectionProfile>()
        .typ::<drift_core::SessionState>()
}

/// Writes the TypeScript bindings to `path`.
pub fn export_bindings(path: &Path) -> Result<(), String> {
    specta_builder()
        .export(
            specta_typescript::Typescript::default().header(
                "// Generated by `cargo xtask bindings` (tauri-specta). Do not edit.\n// @ts-nocheck",
            ),
            path,
        )
        .map_err(|e| e.to_string())
}

/// Runs the application (called from `main`).
///
/// # Panics
/// Panics if the Tauri runtime fails to start (unrecoverable at launch).
pub fn run() {
    let builder = specta_builder();
    #[allow(clippy::expect_used)]
    tauri::Builder::default()
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running Drift");
}
